### ISSUE TITLE
Not random called in quick succession

### ISSUE THREAD

**Issue by qskousen** [elgs/gostrgen#1]
If this function is called in a fast-ish loop, the strings will not be random, because RandGen includes a call to rand.Seed(time.Now().UTC().UnixNano()). Called within the same nano, it will contain the same string. This also has the very undesirable side effect of resetting the rand seed for any other calls to rand in the rest of the program, essentially killing randomness.

Suggest to put the call to rand.Seed(time.Now().UTC().UnixNano()) inside an init() function, so it is called once and once only.

**Comment by elgs** [comment]
Thanks for the awesome point and awesome pull request.
